### ISSUE TITLE
Missing Doxyfile for Doxygen documentation generation

### ISSUE THREAD

**Issue by baijum** [asthra-lang/asthra#109]
## Description
The Doxygen documentation workflow is failing because it's looking for `Doxyfile` but the repository contains `Doxyfile.in`, which is a CMake template that needs to be processed first.

## Error Details
```
error: configuration file Doxyfile not found\!
```

## Workflow Information
- **Workflow**: Build Doxygen Documentation
- **Job URL**: https://github.com/asthra-lang/asthra/actions/runs/15956541080/job/45003597467?pr=108
- **Status**: ❌ Failed

## Root Cause
The repository contains `Doxyfile.in` (a CMake template) instead of a ready-to-use `Doxyfile`. The template contains CMake variables like:
- `@CMAKE_PROJECT_VERSION@`
- `@CMAKE_SOURCE_DIR@`
- `@ASTHRA_DOC_OUTPUT_DIR@`

These need to be substituted by CMake's `configure_file()` command to generate the actual `Doxyfile`.

### Option 1: Update the workflow to use CMake (Recommended)
```yaml
- name: Configure project with CMake
  run: |
    cmake -B build
    # This should generate Doxyfile from Doxyfile.in
    
- name: Generate Doxygen Documentation
  run: |
    cd build  # or wherever CMake generates the Doxyfile
    doxygen Doxyfile
```

### Option 2: Update the workflow to process the template manually
```yaml
- name: Generate Doxyfile from template
  run: |
    sed -e 's|@CMAKE_PROJECT_VERSION@|1.0.0|g' \
        -e 's|@CMAKE_SOURCE_DIR@|.|g' \
        -e 's|@ASTHRA_DOC_OUTPUT_DIR@|docs/html|g' \
        Doxyfile.in > Doxyfile
    
- name: Generate Doxygen Documentation
  run: doxygen Doxyfile
```

## Files Involved
- `Doxyfile.in` - CMake template file (exists)
- `Doxyfile` - Generated configuration file (missing, needs to be generated)
- `.github/workflows/docs-doxygen.yml` - Workflow that needs updating

## Priority
Low - This is not blocking any critical functionality, but documentation generation would be useful for the project.
